#!/usr/bin/perl -w
use utf8;
use strict;use warnings;

open (NAME,"<$ARGV[0]")||die "could not open the name file!";
open (ALL,"<$ARGV[1]")||die "could not open the all file!";

my @id;

while (<NAME>) {
	chomp;
	push(@id,$_);
}

my $flag = 0;
my $i = 0;
my $seq = "";

while (<ALL>) {
	chomp;
	if (/^\>smORF_(\d+)\|Homo sapiens/ and @id != 0) {
		my $num = $1;
		if ($id[0] > $num) {
			$flag = 0;
			next;
		}
		elsif ($id[0] == $num) {
			$flag = 1;
			print "$_\n";
			shift @id;
			next;
		}
		else {
			last;
		}
	}
	else {
		if ($flag == 1) {
			print "$_\n";
			$flag = 0;
			if (@id == 0) {
				last;
			}
			else {
				next;
			}
		}
		else {
			next;
		}
	}
}

close NAME;
close ALL;