#!/usr/bin/perl -w

use utf8;
use strict;use warnings;

open (IN,"<$ARGV[0]") or die "could not open the result file!\n";

my $i = 0;

while (<IN>) {
	chomp;
	if (/[A-Z]+/) {
		$i++;
		my $len = length($_);
		print ">peptide_identified_$i|length:$len\n$_\n";
	}
	else {
		next;
	}
}

close IN;
